### Code test

In [2]:
import numpy as np
s = np.array([0,0,1,0,0,1])
print(s)


[0 0 1 0 0 1]


In [3]:
s

array([0, 0, 1, 0, 0, 1])

In [9]:
ndx = np.where(s==0)[0]
ndx

array([0, 1, 3, 4], dtype=int64)

In [10]:
ndx[2]

3

In [2]:
from proc.generater import *